Add docs to properties that doesn't have docs.
Drachenfrucht1/godotcord pull request #62
Opened 2021-04-17 14:53 UTC by sairam4123

I have been adding docs for the properties which doesn't have docs.
This PR is not yet ready.

2021-04-17 19:11 UTC, summertimejordi requested changes
Try to follow these guidelines
https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html

2021-04-17 19:11 UTC, summertimejordi commented on GodotcordActivity.md
> +- state of the activity if any
Capitalize your sentences

2021-04-17 19:12 UTC, summertimejordi commented
Also you should probably mark this as draft, since it's not finished yet.

2021-04-17 19:16 UTC, sairam4123 commented on GodotcordActivity.md
> +- state of the activity if any
Got it

2021-05-25 02:59 UTC, sairam4123 commented
Could this be closed as XML Docs are being made?

2021-06-10 18:27 UTC, closed without merging